INFO:werkzeug:Press CTRL+C to quit
INFO:root:En eski 'Created' statüsündeki sipariş işleniyor.
INFO:root:Sipariş detayları: [{"barcode": "0799653335880", "converted_barcode": "0799653335880", "color": "Bej", "size": "38", "sku": "099-38 Beige", "productName": "Bej Kumaş Stiletto: Konforlu Vegan Deri Günlük Ve Özel Gün Kadın Topuklu Ayakkabı 099, 38", "productCode": "723303157", "product_main_id": "", "quantity": 1, "total_price": 1149.9, "image_url": "", "line_id": "3975691271", "total_quantity": 1}]
ERROR:root:Bir hata oluştu: (psycopg2.errors.UndefinedColumn) column products.category_name does not exist
LINE 1: ...ucts.product_main_id AS products_product_main_id, products.c...
                                                             ^

[SQL: SELECT products.barcode AS products_barcode, products.original_product_barcode AS products_original_product_barcode, products.title AS products_title, products.hidden AS products_hidden, products.product_main_id AS products_product_main_id, products.category_name AS products_category_name, products.quantity AS products_quantity, products.images AS products_images, products.variants AS products_variants, products.size AS products_size, products.color AS products_color, products.archived AS products_archived, products.locked AS products_locked, products.on_sale AS products_on_sale, products.reject_reason AS products_reject_reason, products.sale_price AS products_sale_price, products.list_price AS products_list_price, products.currency_type AS products_currency_type 
FROM products 
WHERE products.barcode IN (%(barcode_1_1)s)]
[parameters: {'barcode_1_1': '0799653335880'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column products.category_name does not exist
LINE 1: ...ucts.product_main_id AS products_product_main_id, products.c...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/home.py", line 55, in get_home
    products_list = Product.query.filter(Product.barcode.in_(barcodes)).all()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column products.category_name does not exist
LINE 1: ...ucts.product_main_id AS products_product_main_id, products.c...
                                                             ^

[SQL: SELECT products.barcode AS products_barcode, products.original_product_barcode AS products_original_product_barcode, products.title AS products_title, products.hidden AS products_hidden, products.product_main_id AS products_product_main_id, products.category_name AS products_category_name, products.quantity AS products_quantity, products.images AS products_images, products.variants AS products_variants, products.size AS products_size, products.color AS products_color, products.archived AS products_archived, products.locked AS products_locked, products.on_sale AS products_on_sale, products.reject_reason AS products_reject_reason, products.sale_price AS products_sale_price, products.list_price AS products_list_price, products.currency_type AS products_currency_type 
FROM products 
WHERE products.barcode IN (%(barcode_1_1)s)]
[parameters: {'barcode_1_1': '0799653335880'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
INFO:werkzeug:172.31.128.86 - - [06/Mar/2025 18:36:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.31.128.86 - - [06/Mar/2025 18:36:33] "GET /static/logo/gullu.png HTTP/1.1" 304 -
2025-03-06 18:36:36 INFO [app] Veritabanına başarıyla bağlanıldı ve tablolar oluşturuldu.
INFO:app:Veritabanına başarıyla bağlanıldı ve tablolar oluşturuldu.
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "İadeleri Güncelle" to job store "default"
INFO:apscheduler.scheduler:Added job "Ürünleri Güncelle" to job store "default"
INFO:apscheduler.scheduler:Added job "Siparişleri Güncelle" to job store "default"
INFO:apscheduler.scheduler:Added job "İade/Talepleri Güncelle" to job store "default"
INFO:apscheduler.scheduler:Added job "İlk Ürün Güncellemesi" to job store "default"
INFO:apscheduler.scheduler:Added job "İlk Sipariş Güncellemesi" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
2025-03-06 18:36:45 INFO [app] Zamanlayıcı başlatıldı - Otomatik veri güncelleme işleri planlandı
INFO:app:Zamanlayıcı başlatıldı - Otomatik veri güncelleme işleri planlandı
INFO:update_data_service:Sürekli güncelleme sistemi zaten çalışıyor
2025-03-06 18:36:45 INFO [app] Otomatik veri güncelleme sistemi başlatıldı
INFO:app:Otomatik veri güncelleme sistemi başlatıldı
INFO:update_data_service:Sürekli güncelleme sistemi başlatıldı
INFO:update_data_service:--- Güncelleme Döngüsü Başladı ---
INFO:update_data_service:1/3: Siparişler güncelleniyor...
INFO:update_data_service:Siparişler güncellenmeye başlanıyor...
WARNING:apscheduler.executors.default:Run time of job "İlk Ürün Güncellemesi (trigger: date[2025-03-06 18:37:45 +03], next run at: 2025-03-06 18:37:45 +03)" was missed by 2:59:00.007881
INFO:apscheduler.scheduler:Removed job initial_products_job
INFO:apscheduler.scheduler:Removed job initial_orders_job
WARNING:apscheduler.executors.default:Run time of job "İlk Sipariş Güncellemesi (trigger: date[2025-03-06 18:38:45 +03], next run at: 2025-03-06 18:38:45 +03)" was missed by 2:58:00.015598
Toplam sipariş sayısı: 655, Toplam sayfa sayısı: 4
Toplam çekilen sipariş sayısı: 655
