"line_id": "3991540946", "total_quantity": 1}]
ERROR:root:Bir hata oluştu: (psycopg2.errors.UndefinedColumn) column products.cost_date does not exist
LINE 1: ...ncy_type, products.cost_usd AS products_cost_usd, products.c...
                                                             ^

[SQL: SELECT products.barcode AS products_barcode, products.original_product_barcode AS products_original_product_barcode, products.title AS products_title, products.hidden AS products_hidden, products.product_main_id AS products_product_main_id, products.quantity AS products_quantity, products.images AS products_images, products.variants AS products_variants, products.size AS products_size, products.color AS products_color, products.archived AS products_archived, products.locked AS products_locked, products.on_sale AS products_on_sale, products.reject_reason AS products_reject_reason, products.sale_price AS products_sale_price, products.list_price AS products_list_price, products.currency_type AS products_currency_type, products.cost_usd AS products_cost_usd, products.cost_date AS products_cost_date 
FROM products 
WHERE products.barcode IN (%(barcode_1_1)s)]
[parameters: {'barcode_1_1': 'Güllüayakkabı01'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column products.cost_date does not exist
LINE 1: ...ncy_type, products.cost_usd AS products_cost_usd, products.c...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/home.py", line 55, in get_home
    products_list = Product.query.filter(Product.barcode.in_(barcodes)).all()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column products.cost_date does not exist
LINE 1: ...ncy_type, products.cost_usd AS products_cost_usd, products.c...
                                                             ^

[SQL: SELECT products.barcode AS products_barcode, products.original_product_barcode AS products_original_product_barcode, products.title AS products_title, products.hidden AS products_hidden, products.product_main_id AS products_product_main_id, products.quantity AS products_quantity, products.images AS products_images, products.variants AS products_variants, products.size AS products_size, products.color AS products_color, products.archived AS products_archived, products.locked AS products_locked, products.on_sale AS products_on_sale, products.reject_reason AS products_reject_reason, products.sale_price AS products_sale_price, products.list_price AS products_list_price, products.currency_type AS products_currency_type, products.cost_usd AS products_cost_usd, products.cost_date AS products_cost_date 
FROM products 
WHERE products.barcode IN (%(barcode_1_1)s)]
[parameters: {'barcode_1_1': 'Güllüayakkabı01'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:26] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:26] "GET /static/logo/gullu.png HTTP/1.1" 304 -
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:31] "GET /iade-listesi HTTP/1.1" 200 -
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:31] "GET /static/logo/gullu.png HTTP/1.1" 304 -
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:35] "GET /home HTTP/1.1" 200 -
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:35] "GET /static/logo/gullu.png HTTP/1.1" 304 -
ERROR:get_products:Ürünler veritabanından çekilirken bir hata oluştu: (psycopg2.errors.UndefinedColumn) column products.cost_date does not exist
LINE 1: ...ncy_type, products.cost_usd AS products_cost_usd, products.c...
                                                             ^

[SQL: SELECT products.barcode AS products_barcode, products.original_product_barcode AS products_original_product_barcode, products.title AS products_title, products.hidden AS products_hidden, products.product_main_id AS products_product_main_id, products.quantity AS products_quantity, products.images AS products_images, products.variants AS products_variants, products.size AS products_size, products.color AS products_color, products.archived AS products_archived, products.locked AS products_locked, products.on_sale AS products_on_sale, products.reject_reason AS products_reject_reason, products.sale_price AS products_sale_price, products.list_price AS products_list_price, products.currency_type AS products_currency_type, products.cost_usd AS products_cost_usd, products.cost_date AS products_cost_date 
FROM products]
(Background on this error at: https://sqlalche.me/e/20/f405)
INFO:werkzeug:172.31.128.49 - - [12/Mar/2025 00:34:39] "GET /product_list HTTP/1.1" 200 -